StylesPath = styles
MinAlertLevel = warning

Packages = write-good, proselint

[*.md]
BasedOnStyles = write-good, proselint

# write-good tuning — too noisy for technical writing
write-good.TooWordy = NO
write-good.So = NO
proselint.Very = NO
proselint.Cliches = NO
proselint.Typography = NO
